### PR TITLE
 Use UserCallbacks instead of Export.lua

### PR DESCRIPTION
**Pull request by bjanders**
- No need to mess with the Export.lua file
- Updated README.md accordingly
- Fixed log path so that it is not hard coded to frank's folder
- Commented out Data.txt logging for now. Should be fixed separately so
  that it is done in onSimulationFrame() but only 10 times/sec.

### CODE REVIEW

**Comment by Dirt-e** [comment]
Ohhh,.... Nice to see this pull request!

I was always wondering if it was actually necessary to mess with the Export.lua or if there was another way. So, if I understand correctly you can just throw that Nutkicker.lua file in the /Hooks folder and it will run the code, right? Is there even an Export.lua file necessary then? 

As you can probably tell, I have virtually no experience at all in Lua. In fact, THIS is my first programming project ever. I learned programming just for this project. So in case you are wondering about some strange programming practices,.... that't the reason why :-D

**Comment by bjanders** [comment]
Yes, just place the Nutkicker.lua file in the Scripts/Hooks folder; no Export.lua needed.

I'm quite new to Lua as well and the DCS integration framework. A year ago I made an Export.lua script myself (which is my first and only Lua program), and just this week I learned about the Hooks folder. The biggest issue with the Export.lua is that if someone else wants to add their plugin as well, then everybody has to edit the Export.lua. With Hooks folder you just drop in your own script. Export.lua and Hooks don't have the exact same feature available to them, but for your case the Hooks will provide what you need, and I think it is therefore the prefreable way.

**Comment by Dirt-e** [comment]
Hey Björn,

Thanks! Using the callbacks is absolutely fantastic. One thing I noticed (and maybe you can confirm) is that DCS loads the code contained in the /Hooks folder only on program start, and not when re-loading the mission. I spend an hour wondering why my changes in the files had no effect, until I specifically checked for that. 😁

Thanks again

**Comment by bjanders** [comment]
Yes, sorry, I should have mentioned it, but forgot. I noticed it too, and it is definitively a drawback, even when you know about it as changing the code requires that you restart the whole game. Another thing that is annoying with the Hooks compared to Export.lua is that errors in the code are not logged, or at least not what I have noticed, which makes it much more difficult to debug. I'm almost starting to think that using the Hooks is not a good idea after all, at least not during the development stage.

Some kind of combined solution would be the ideal, specifically so that you can add your own plugin script without having to care about other plugins (like one currently has to with Export.lua). I had proposed a better solution for Eagle Dynamics in the DCS forums, which is when someone told me about the Hooks.

**Comment by Dirt-e** [comment]
Yeah, for development I thought the same thing: Better try out changes in the Export.lua directly.
But distribution code will definitely get the Hooks :-)

**Pull request merged**
